# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20170723_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='academic',
            field=models.CharField(choices=[('1', 'Academic'), ('2', 'Office')], max_length=1),
        ),
    ]
