# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20170726_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='academic_or_office',
            field=models.CharField(choices=[('1', 'Academic'), ('2', 'Office')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.CharField(default='', max_length=20),
        ),
    ]
