# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20170723_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='academic',
            new_name='academic_or_office',
        ),
    ]
