# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20170723_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
