# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20170723_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='marketplace/static/marketplace/img/default.png', upload_to='marketplace/static/marketplace/img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.User'),
        ),
        migrations.AddField(
            model_name='tag',
            name='pics',
            field=models.ManyToManyField(blank=True, to='marketplace.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='marketplace.Tag'),
        ),
    ]
