# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20170726_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='marketplace/static/img/'),
        ),
    ]
