# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='pics',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
