# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auto_20170726_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='academic_or_office',
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('1', 'Academic'), ('2', 'Office')], default='', max_length=1),
        ),
    ]
