# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20170726_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Office', 'Office')], default='', max_length=1),
        ),
    ]
