# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='secondhand',
            field=models.CharField(max_length=50),
        ),
    ]
