# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_auto_20170813_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='marketplace.Post'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='secondhand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondhand', to='marketplace.Post'),
        ),
    ]
