# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_auto_20170813_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='approve_reject',
            field=models.NullBooleanField(),
        ),
    ]
