# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_offer_approve_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
